MNT: rerender
conda-forge/cudnn-feedstock pull request #24
Opened 2021-06-22 18:21 UTC by conda-forge-linter

Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #23.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #23

2021-06-22 18:21 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * The recipe `license` should not include the word "License".
 * There are too few lines.  There should be one empty line at the end of the file.

For **recipe**:

 * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.

Documentation on acceptable licenses can be found [here]( https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions ).

2021-06-22 19:00 UTC, leofang requested changes

2021-06-22 19:00 UTC, leofang commented on .ci_support/win_64_cuda_compiler_version10.2.yaml
> -- win-64
Removing this file is incorrect...

2021-06-22 19:55 UTC, isuruf commented
@conda-forge-admin, rerender

2021-06-23 01:34 UTC, leofang commented
Interesting...Thanks @isuruf. Is there a reason we striped off most of the content in `cuda111_112.yaml`?

2021-06-23 02:28 UTC, closed without merging

2021-06-23 04:03 UTC, isuruf commented
They are not strictly necessary as conda-smithy gets them from conda-forge-pinning. Btw, in the future please don't take my commits without giving credit. (Use the commit as is or mention in the new commit message)