v8.5
conda-forge/cudnn-feedstock pull request #48
Opened 2022-10-07 03:50 UTC by ngam

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-10-07 03:50 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-10-07 17:48 UTC, jakirkham requested changes
As we are still working through cuDNN 8.5 support on conda-forge internally, we cannot merge this PR at present.

2022-10-07 18:19 UTC, closed without merging

2023-03-03 07:33 UTC, riturajkumar1468 commented
@ngam can we get cudnn 8.5 merged now?

2023-03-03 07:39 UTC, riturajkumar1468 commented
@kkraus14 can we have cudnn 8.5 bumped up now